SCHTASKS /CREATE /SC DAILY /TN "MICROSOFT\Alpha_API" /TR "C:\Users\bd6612\Scripts\alphavantage_API.py" /ST 12:11 /RU "BD6612" /RL HIGHEST
SCHTASKS /CREATE /SC DAILY /TN "MICROSOFT\Alpha_APIread" /TR "C:\Users\bd6612\Scripts\readAlphaAPI.py" /ST 12:11 /RU "BD6612" /RL HIGHEST
SCHTASKS /QUERY /TN "MICROSOFT\Alpha_API"
SCHTASKS /QUERY /TN "MICROSOFT\Alpha_APIread"
